In [2]:
from src.visualization import plot_cqt

In [7]:
from src.data_utils.preprocessing import *
import os

In [4]:
audio_path = 'data/raw/D0/A0-B0-D0-e0-Eb0-G0-fpick/D0_fingerpick-01.wav'

In [9]:
PARENT_DIR = os.path.dirname(os.getcwd())  # Get the parent of the current CWD
os.chdir(PARENT_DIR)

In [22]:
audio, sr = load_audio(audio_path)

In [23]:
audio

array([-6.8634748e-05, -6.3233078e-05,  9.9316239e-05, ...,
        3.1036502e-04,  3.9156686e-04,  2.4417910e-04], dtype=float32)

In [24]:
cqt = audio_to_cqt(audio, sr)
cqt

C:\Users\User\PycharmProjects\guitar-tabs-classification\src\preprocessing.py:20: UserWarning: amplitude_to_db was called on complex input so phase information will be discarded. To suppress this warning, call amplitude_to_db(np.abs(S)) instead.
  cqt = librosa.amplitude_to_db(librosa.cqt(harmonic, sr=sr), ref=np.max)


array([[-61.032898, -61.15428 , -61.931465, ..., -80.      , -80.      ,
        -80.      ],
       [-59.963448, -59.914207, -60.27584 , ..., -77.91877 , -77.98291 ,
        -78.59618 ],
       [-59.854347, -59.63587 , -61.388374, ..., -70.592224, -73.85099 ,
        -73.69144 ],
       ...,
       [-55.06804 , -54.073265, -55.00875 , ..., -80.      , -80.      ,
        -80.      ],
       [-54.696075, -56.07144 , -62.111374, ..., -80.      , -80.      ,
        -80.      ],
       [-55.05065 , -59.484184, -65.23612 , ..., -80.      , -80.      ,
        -80.      ]], dtype=float32)

In [26]:
cqt = normalize_cqt(cqt)
cqt

array([[-0.1112024 , -0.11728164, -0.15620516, ..., -1.0611279 ,
        -1.0611279 , -1.0611279 ],
       [-0.05764133, -0.05517525, -0.07328686, ..., -0.9568941 ,
        -0.96010643, -0.9908209 ],
       [-0.05217728, -0.04123543, -0.12900566, ..., -0.5899602 ,
        -0.7531683 , -0.74517745],
       ...,
       [ 0.18753442,  0.23735547,  0.19050373, ..., -1.0611279 ,
        -1.0611279 , -1.0611279 ],
       [ 0.20616339,  0.13728121, -0.16521549, ..., -1.0611279 ,
        -1.0611279 , -1.0611279 ],
       [ 0.18840523, -0.03363849, -0.32171163, ..., -1.0611279 ,
        -1.0611279 , -1.0611279 ]], dtype=float32)

In [1]:
plot_cqt(cqt, sr)

NameError: name 'plot_cqt' is not defined